POST /register HTTP/1.1
Host: localhost:8080
User-Agent: client android
Accept: application/json
Content-Type: application/json

{
  "email": "email@uy.ru",
  "password": "password",
  "name": "Дмитрий"
}